//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobclubBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int JobApplicationid { get; set; }
        public Nullable<int> Jobid { get; set; }
        public Nullable<int> Companyid { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string resumepath { get; set; }
    }
}
