//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobclubBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimebizjobsEntities : DbContext
    {
        public TimebizjobsEntities()
            : base("name=TimebizjobsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TimebizCategory> TimebizCategories { get; set; }
        public virtual DbSet<TimebizDistrict> TimebizDistricts { get; set; }
        public virtual DbSet<TimebizCompany> TimebizCompanies { get; set; }
        public virtual DbSet<TimebizJob> TimebizJobs { get; set; }
        public virtual DbSet<Timebizuser> Timebizusers { get; set; }
        public virtual DbSet<JobApplication> JobApplications { get; set; }
    }
}
