//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobclubBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimebizCategory
    {
        public int Categoryid { get; set; }
        public string Category { get; set; }
        public string Imagepath { get; set; }
    }
}
