//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobclubBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timebizuser
    {
        public int Userid { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Roles { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string Name { get; set; }
        public string Mobileno { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string CurrentCompany { get; set; }
        public string Experience { get; set; }
        public string Skills { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string UserImagePath { get; set; }
        public string ResumePath { get; set; }
        public string Email { get; set; }
        public Nullable<int> Companyid { get; set; }
        public string qualitfications { get; set; }
    }
}
