//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobclubBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimebizCompany
    {
        public int Companyid { get; set; }
        public string Companyname { get; set; }
        public string Website { get; set; }
        public string Mobileno { get; set; }
        public string Phoneno { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Imagepath { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string District { get; set; }
        public Nullable<int> Userid { get; set; }
        public string islogincreated { get; set; }
    }
}
