//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobclubBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimebizJob
    {
        public int Jobid { get; set; }
        public string JobTitle { get; set; }
        public string JobType { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string Designation { get; set; }
        public string Description { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Companyname { get; set; }
        public string Website { get; set; }
        public string Phoneno { get; set; }
        public string Email { get; set; }
        public Nullable<int> Vacancy { get; set; }
        public string Jobworkday { get; set; }
        public string Jobworktime { get; set; }
        public string Address { get; set; }
        public string Experience { get; set; }
        public string Qualification { get; set; }
        public string Skills { get; set; }
        public string FeaturedImagepath { get; set; }
        public Nullable<System.DateTime> DateOfInterview { get; set; }
        public Nullable<int> Companyid { get; set; }
        public string Category { get; set; }
    }
}
